docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u marce1in -p "$DOCKER_HUB_TOKEN"

  script:
    - docker build \
        --pull \
        --build-arg VITE_APP_NAME="$VITE_APP_NAME" \
        --build-arg VITE_REVERB_APP_KEY="$VITE_REVERB_APP_KEY" \
        --build-arg VITE_REVERB_HOST="$VITE_REVERB_HOST" \
        --build-arg VITE_REVERB_SCHEME="$VITE_REVERB_SCHEME" \
        -t "marce1in/meira:latest" .

    - docker push "marce1in/meira:latest"

  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      exists:
        - Dockerfile
