services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: meira:latest
    network_mode: host
    command: php artisan octane:frankenphp --host=0.0.0.0
    env_file:
      - .env

  queue:
    image: meira:latest
    network_mode: host
    command: php artisan queue:work --tries=3 --max-time=3600
    env_file:
      - .env
    depends_on:
      - app

  reverb:
    image: meira:latest
    network_mode: host
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    env_file:
      - .env
    depends_on:
      - app

  inertia-ssr:
    image: meira:latest
    network_mode: host
    command: php artisan inertia:start-ssr
    env_file:
      - .env
    depends_on:
      - app
