services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_NAME: ${VITE_APP_NAME}
        VITE_REVERB_APP_KEY: ${VITE_REVERB_APP_KEY}
        VITE_REVERB_HOST: ${VITE_REVERB_HOST}
        VITE_REVERB_PORT: ${VITE_REVERB_PORT}
        VITE_REVERB_SCHEME: ${VITE_REVERB_SCHEME}
    network_mode: host
    env_file: .env
    volumes:
      - ./:/app:z
