# fly.toml app configuration file generated for meira-woro on 2025-09-20T17:35:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meira-woro'
primary_region = 'gru'
console_command = 'php /var/www/html/artisan tinker'
swap_size_mb = 124

[deploy]
release_command = 'php artisan migrate --force'

[build.args]
VITE_APP_NAME = 'Meira'
VITE_REVERB_APP_KEY = 'vilz1hsaxbzohc0i7pwi'
VITE_REVERB_HOST = 'meira.marce1in.com.br'
VITE_REVERB_PORT = '8080'
VITE_REVERB_SCHEME = 'http'

[env]
APP_NAME = 'Meira'
APP_DEBUG = 'false'
APP_ENV = 'production'

APP_MAINTENANCE_DRIVER = 'file'

APP_LOCALE = 'en'
APP_FALLBACK_LOCALE = 'en'
APP_FAKER_LOCALE = 'en_US'

BCRYPT_ROUNDS = '12'

LOG_CHANNEL = 'stderr'
LOG_LEVEL = 'info'
LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'

SESSION_DRIVER = 'database'
SESSION_LIFETIME = '120'
SESSION_ENCRYPT = 'false'
SESSION_PATH = '/'
SESSION_DOMAIN = 'null'

BROADCAST_CONNECTION = 'reverb'
FILESYSTEM_DISK = 'local'
QUEUE_CONNECTION = 'database'

CACHE_STORE = 'database'

WORKOS_REDIRECT_URL = "https://meira.marce1in.com.br/authenticate"

REVERB_APP_ID = '836335'
REVERB_APP_KEY = 'vilz1hsaxbzohc0i7pwi'
REVERB_HOST = 'localhost'
REVERB_PORT = '8080'
REVERB_SCHEME = 'http'

[[services]]
protocol = 'tcp'
internal_port = 8000

[[services.ports]]
port = 80
handlers = ['http']
force_https = true

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[services.concurrency]
type = 'connections'
hard_limit = 200
soft_limit = 150

[[services.http_checks]]
interval = '15s'
timeout = '5s'
grace_period = '30s'
method = 'GET'
path = '/up'
protocol = 'http'

[[services]]
protocol = 'tcp'
internal_port = 8080

[[services.ports]]
port = 8080
handlers = ['tls', 'http']

[[vm]]
size = 'shared-cpu-1x'
memory = '1gb'
